### Criar um novo lutador
POST http://localhost:3000/api/fighters/
Content-Type: application/json

{
  "name": "Marcio R",
  "team": "G13BJJ",
  "style": "Passador",
  "overall": 10
}

### Criar uma nova tecnica
POST http://localhost:3000/api/techniques/
Content-Type: application/json

{
  "name": "Leandro Lo's Baiana",
  "type": "Takedown",
  "points": 100
}