### Lista todos os lutadores
GET http://localhost:3000/api/fighters/all
Content-Type: application/json

### Luta
GET http://localhost:3000/api/fighters/fight/2/1
Content-Type: application/json

### Pesquisa por um lutador
GET http://localhost:3000/api/fighters/6
Content-Type: application/json