### Lista todos os lutadores
GET http://localhost:3000/api/fighters/
Content-Type: application/json

### Luta
GET http://localhost:3000/api/fighters/fight/3/1
Content-Type: application/json

### Pesquisa por um lutador
GET http://localhost:3000/api/fighters/2
Content-Type: application/json

### Lista todas as tecnicas
GET http://localhost:3000/api/techniques/
Content-Type: application/json