### Criar um novo lutador
PATCH http://localhost:3000/api/fighters/5
Content-Type: application/json

{
  "overall": 1
}

### Atualiza partidas/rolas/matches
PATCH http://localhost:3000/api/fighters/matches/1
Content-Type: application/json

{
  "matches": 252
}